# Default values.
#
# NOTE: This file does not attempt to represent all possible changeable values in the subscharts.
# It only attempts to contain values that might be changed more often.  
# If a values is not listed here, the subchart's values are used.
#

name: central_logging

central:
  ci_testing: false
  publc: true
  test:
    image: quay.io/samsung_cnct/e2etester:prod
    account: elastic
    password: changeme

#
# Only used if central.public: true  above
#
external-dns:
  aws:
    # These are the credentials for an aws user than can manipulate route53
    # They must be supplied on the command line e.g.:
    # --set external-dns.aws.secretKey="value1",external-dns.aws.accessKey="value2".
    #
    # If these are invalid, the public DN for elasticsearch will not be created
    secretKey: SET_ON_COMMAND_LINE
    accessKey: SET_ON_COMMAND_LINE
    roleArn: ""
    region: "us-west-2"
    # Filter for zones of this type (optional, options: public, private)
    zoneType: ""
  #
  # The following is the base FQDN for the services we need.
  # The baseDomain has to be set up by hand in route53 before installing this chart.
  # replace with your domain.
  #
  # this can be set on the commmand line as; 
  # external-dns.domainFilters[0]="external-dns.alpha.kubernetes.io/hostname"
  #
  domainFilters: [ "<mydomain>.cluster.cnct.io" ]
  rbac:
    create: true

elasticsearch-chart:
  name: elasticsearch
  port: 9200

  data_memory_limits: 16Gi
  data_memory_requests: 16Gi
  data_Xms_Xmx: 8g
  # master_memory_limits: 2Gi
  # master_memory_requests: 2Gi
  # master_Xms_Xmx: 1g

  security:
    password: "changeme"
  services:
    es:
      public: true
      # this can be set on the commmand line as; 
      # elasticsearch-chart.services.es.annotations[0].key="external-dns.alpha.kubernetes.io/hostname",elasticsearch-chart.services.es.annotations[0].value=esold.mikeln.cluster.cnct.io
      annotations:
      - key: "external-dns.alpha.kubernetes.io/hostname"
        value: "es.<newdomain>.cluster.cnct.io" 

kibana:
  name: kibana
  port: 5601
  security:
    password: "changeme"
  cpu_limit: 100m
  cpu_requests: 100m
  mem_limit: 512Mi
  mem_requests: 512Mi

curator:
  name: curator
  schedule: "30 3 * * *"
  action: delete_indices
  security:
    password: "changme"
  
  logstashFilters:
    direction: older
    unit: days
    unit_count: 14
  
  logsystemdFilters:
    direction: older
    unit: days
    unit_count: 14
  
  logging:
    loglevel: INFO
